language: php

php:
  - "5.5"
  - "5.4"

before_script:
  - composer install --dev

after_script:
  - vendor/bin/test-reporter

addons:
  code_climate:
    repo_token: 3f6cdd21259a61b22c0c355e09d41d0ee2bb5568fa744071de89bf4df7d1a8e6
